# Generated by Django 5.2.7 on 2025-10-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('appId', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('phones', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddress', models.CharField(max_length=64, unique=True)),
                ('os', models.CharField(max_length=64)),
                ('brandName', models.CharField(blank=True, max_length=64, null=True)),
                ('modelName', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('businessId', models.SlugField(max_length=32, unique=True)),
                ('domain', models.CharField(blank=True, max_length=128, null=True)),
                ('owner', models.ManyToManyField(blank=True, null=True, related_name='businesses', to='LicensingApp.businessowner')),
                ('machines', models.ManyToManyField(blank=True, related_name='businesses', to='LicensingApp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenseKey', models.SlugField(max_length=64, unique=True)),
                ('validTill', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='LicensingApp.app')),
                ('business', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='LicensingApp.clientbusiness')),
            ],
        ),
    ]
