# Generated by Django 5.2.7 on 2025-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
