# Generated by Django 5.2.7 on 2025-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='ownerid',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
