# Generated by Django 5.2.7 on 2025-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0002_alter_businessowner_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbusiness',
            name='appsOwned',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='ownedLicenses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
