# Generated by Django 5.2.7 on 2025-10-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0003_clientbusiness_appsowned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbusiness',
            old_name='owner',
            new_name='ownerIds',
        ),
    ]
