# Generated by Django 5.2.7 on 2025-10-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0004_rename_owner_clientbusiness_ownerids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbusiness',
            old_name='ownerIds',
            new_name='owner',
        ),
    ]
