# Generated by Django 5.2.7 on 2025-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0005_rename_ownerids_clientbusiness_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbusiness',
            old_name='ownedLicenses',
            new_name='ownedLicensesList',
        ),
    ]
