# Generated by Django 5.2.7 on 2025-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0006_rename_ownedlicenses_clientbusiness_ownedlicenseslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbusiness',
            name='appsOwned',
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='appsOwned',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_by_businesses', to='LicensingApp.app'),
        ),
    ]
