# Generated by Django 5.2.7 on 2025-10-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensingApp', '0007_remove_clientbusiness_appsowned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbusiness',
            name='appsOwned',
            field=models.ManyToManyField(blank=True, related_name='owned_by_businesses', to='LicensingApp.app'),
        ),
        migrations.RemoveField(
            model_name='clientbusiness',
            name='ownedLicensesList',
        ),
        migrations.AlterField(
            model_name='clientbusiness',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='LicensingApp.businessowner'),
        ),
        migrations.AlterField(
            model_name='license',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='LicensingApp.clientbusiness'),
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='ownedLicensesList',
            field=models.ManyToManyField(blank=True, related_name='owned_by_businesses', to='LicensingApp.license'),
        ),
    ]
